# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.
services:
  catalog.db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./db/catalogdb_data:/var/lib/mongodb/data
    ports:
      - 27017:27017

  catalog.api:
    image: 1811063460/catalog.api:latest
    build:
      context: .
      dockerfile: src/Services/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MongoDb=mongodb://root:123456@catalog.db:27017
    ports:
      - "5000:80"
    depends_on:
      - catalog.db

volumes:
  catalogdb_data:
