services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./db/mongodb_data:/data/db ### Fix Db location of mongoDb
    ports:
      - 27017:27017 ## Port must be 27017 do not change it
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=BasketDb
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=mongodb://root:123456@mongo:27017
      - MongoDb__Host=mongo
      - MongoDb__Credentials__UserName=root
      - MongoDb__Credentials__Password=123456
    ports:
      - "6000:8080"
      - "6060:8081"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Marten=Server=postgres;Port=5432;Database=BasketDb;User Id=postgres;Password=123456;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"

  keycloak:
    container_name: keycloak
    command: start-dev # Run the keycloak in dev mode https://www.keycloak.org/nightly/server/containers
    environment:
      # Enable health and metrics support
      - KC_HEALTH_ENABLED=true
      - ENV KC_METRICS_ENABLED=true
      # Configure Keycloak admin credentials
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./db/identity:/opt/keycloak/data
    ports:
      - 18080:8080

  distributedcache:
    container_name: distributedcache
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis_data:/data
  redis-commander:
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=BasketCache:distributedcache:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 7001:8081
    depends_on:
      - distributedcache
